### PR TITLE
Flesh out /ide endpoint to eventually replace /editor

### PR DESCRIPTION
**Pull request by pcardune**
Starting to flesh out where a refactored version of /editor is going to live until it is ready.

### CODE REVIEW

**Comment by jpolitz** [comment]
I'm getting this error when running `npm install`:


```
Version: webpack 1.13.1
Time: 2568ms
      Asset    Size  Chunks             Chunk Names
PyretIDE.js  713 kB       0  [emitted]  PyretIDE
    + 139 hidden modules

ERROR in ./src/components/CodeWindow.js
Module not found: Error: Cannot resolve module 'style' in /Users/joe/src/cpo-merges/node_modules/pyret-ide/src/components
 @ ./src/components/CodeWindow.js 17:0-40

ERROR in ./src/components/CodeWindow.js
Module not found: Error: Cannot resolve module 'style' in /Users/joe/src/cpo-merges/node_modules/pyret-ide/src/components
 @ ./src/components/CodeWindow.js 19:0-39
```

Also, when I load `localhost:5000/ide`, I get:

```
Uncaught Error: Cannot find module "codemirror/lib/codemirror.css"
webpackMissingModule @ PyretIDE.js:9699(anonymous function)
```

Is this a problem on my end?

**Comment by pcardune** [comment]
nope, those are problems on my end. I'm going to pin the revision that gets pulled in for pyret-ide so our work there doesn't destabilize anything in code.pyret.org. Will submit an update to this pull request.

**Comment by pcardune** [comment]
ok @jpolitz, that problem should be fixed. please give it another try.

**Comment by jpolitz** [comment]
This builds and runs cleanly for me now.  Think this looks good!

**Pull request merged**
