### PR TITLE
Add plot lib to master

### PR DESCRIPTION
**Pull request by sorawee**
@SDooman @jpolitz

### CODE REVIEW

**Comment by jpolitz** [comment]
Question @sorawee / @SDooman why did the names of functions need to change?

**Comment by jpolitz** [comment]
If someone could add a commit that puts the old names back (and make sure they work), that would be useful – we broke some teachers' code with this change.

**Comment by sorawee** [comment]
Recall that this is a feedback from @blerner. I can definitely change it back if that causes a problem.

**Comment by blerner** [comment]
I don't remember saying that, but it sounds plausible...
Separately, does this include the fix for plot window margins that Jen requested for the physics usages?

**Comment by jpolitz** [comment]
I totally believe that it makes sense, I just wanted the reason documented on the PR.  I don't think that we should change back, but we should leave the old names in.  I think just aliasing the new names to the old ones and providing both makes sense.

**Comment by sorawee** [comment]
@blerner does not have the fix yet. Will do it today.

@jpolitz will alias the old name to the new name now.

**Comment by sorawee** [comment]
I recall it now. Ben did not suggest changing this, but suggest changing `x-scale` to `extend-x`. Changing from `display-` to `render-` is mine, and the reason is that with `interact` setting to `false`, there's no display and the function just returns an image value, so naming it `display-` is misleading.

Anyway, I make aliases to `display-`. Will submit a PR soon.

**Pull request merged**
