### PR TITLE
fixes #231

### LINKED ISSUE #231: Support Apple shortcut keys
Ctrl-S -> Cmd-S on MacOS

### PR DESCRIPTION
**Pull request by YanyanR**
All the "Ctrl" keyboard shortcut now also works with "Cmd", e.g. both "Ctrl-s" and "Cmd-s" saves the file. @schanzer

### CODE REVIEW

**Comment by blerner** [comment]
This needs to be tested on Windows machines too, on Chrome and Firefox: the meta key is *sometimes* mapped to the Windows key instead (and I can't find reliable information online about it right now), which isn't what would be expected on a Windows machine.

**Comment by YanyanR** [comment]
On Windows keyboards, this is the windows key (⊞). (source: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey)

But I think this is fine, if we support both. 
On windows computer, they can still use "Ctrl-s" to save. Even if someone accidentally use "Windows-s", then that's also fine. On Mac, default "Cmd-s" will save the html file, but I don't think anyone would have use for that.

**Comment by blerner** [comment]
No, on Windows, the Windows+S combination is already in use, for system-wide search.  Actually, almost all Windows+letter combinations mean something, so we should avoid checking for it.  Your code will need to check whether it's on mac or windows, before checking for the meta key.

**Comment by jpolitz** [comment]
If no one else gets to it before then, I'll check it at some point over the weekend; I have a Windows machine at home.

**Comment by YanyanR** [comment]
Is it worth using [navigator.platform](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/platform) here to detect windows/mac? (It returns a string representing the platform of the browser.) 

Another question, when testing windows vs mac, have you used Safari's User Agent under Develop menu? Does it work well, or it's still better to test on a windows machine?

**Comment by jpolitz** [comment]
I think we should probably look up keybinding libraries if we want to do this right.

I usually want to try on a keyboard that looks like a Windows keyboard for things like this (and also test in Edge).

**Comment by jpolitz** [comment]
Though it's certainly not a _bad_ idea to try out the Safari mode :-) 

We'll know a little more about how good it is if we test in both ways.

**Comment by YanyanR** [comment]
When you say "keybinding libraries", do you mean finding out if the combinations are already in use?
 
If so here's the list for [Windows 10](https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts):
- Windows-S: Open search
- Windows-M: Minimize all windows
- Windows-Enter: Open Narrator
- Windows-?: nothing

But then we'll also need to consider different browsers' shortcut, like [Chrome shortcut](https://support.google.com/chrome/answer/157179?hl=en), and different OS versions (win7 vs win8)? And should we consider linux too?

**Comment by jpolitz** [comment]
I mean like https://craig.is/killing/mice or
https://github.com/RobertWHurst/KeyboardJS

**Comment by YanyanR** [comment]
[This commit](214457f7aea8d8a0e840b958db48039c15ff94d0) is about adding [mousetrap library](https://craig.is/killing/mice), which has a generic `mod` helper that lets you set cross platform shortcuts. On Mac this ends up mapping to `command+s` whereas on Windows and Linux it maps to `ctrl+s`. 

@jpolitz could you test it on a windows machine? Safari's user agent only sets the browser but not the keyboard.

**Comment by jpolitz** [comment]
I'm merging this so I can more easily test it. I started spending way too much time doing the right local install for windows, and I don't think it'll hurt anything for it to be on horizon for testing.

**Pull request merged**
