### PR TITLE
This should be a locator, not a located

### PR DESCRIPTION
**Pull request by sorawee**
@jpolitz

### CODE REVIEW

**Comment by awstlaur** [comment]
The issue referencing this pull request was closed, which makes me think this pull request wants to be closed as well.

**Comment by sorawee** [comment]
I closed it because I submitted the PR!

**Comment by blerner** [comment]
@sorawee I think this PR can be closed -- this file no longer exists as such, and in cpo-main.js where the code's moved to, it seems like it's now more right than this PR is.  Could you confirm and close?

**Comment by sorawee** [comment]
Yup! (also, I will try to do all stuff I promised to do this weekend. Really apologize for the late)

**Pull request closed without merging**
